# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4

    - name: ensure vendor files
      run: go mod tidy && go mod vendor

    # - name: list files
    #   run: ls -al vendor/github.com/pemistahl/lingua-go
    
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.23"
        project_path: "./cmd/picam-streamer"
        binary_name: "picam-streamer"
        ldflags: -X github.com/ylallemant/go-picam-streamer/pkg/binary.repository=${{github.repositoryUrl}} -X github.com/ylallemant/go-picam-streamer/pkg/binary.gitCommitHash=${{github.sha}} -X github.com/ylallemant/go-picam-streamer/pkg/binary.semverVersion=${{ github.ref_name }}
        #extra_files: LICENSE README.md